stages:
  - deploy
  - update
  - restart

deploy:
  stage: deploy
  script:
    - rsync -av ./ ${BOT_PATH} --exclude .git
  environment:
    name: deploy
  only:
    - master

update:
  stage: update
  script:
    - cd ${BOT_PATH}
    - yarn install
  environment:
    name: deploy
  only:
    - master

restart:
  stage: restart
  script:
    - env HOME=/home/pm2 pm2 restart bot
  environment:
    name: restart
  only:
    - /RESTART_BOT/
    - master

restart-manual:
  stage: restart
  script:
    - env HOME=/home/pm2 pm2 restart bot
  when: manual
  environment:
    name: restart
  only:
    - master
  except:
    - /RESTART_BOT/
